name: Update Malicious URLs

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 2 minutes

jobs:
  update-malicious-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get and echo malicious URLs
        run: |
          MALICIOUS_URLS=$(curl -sSf https://urlhaus.abuse.ch/downloads/text/)
          echo "$MALICIOUS_URLS"
