name: Update Malicious URLs

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'  # Run every 2 minutes
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-malicious-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get malicious URLs
        run: |
          MALICIOUS_URLS=$(curl -sSf https://urlhaus.abuse.ch/downloads/text/)
          echo "$MALICIOUS_URLS" > maliciousURLs.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "umairnehri9747@gmail.com"
          git config --global user.name "Umair Nehri - GitHub Actions"

          git add maliciousURLs.txt
          git commit -m "Update malicious URLs [skip ci]"
          git push
