name: Update Malicious URLs

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-malicious-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete existing URL file
        run: |
          rm -f maliciousURLs.txt

      - name: Get and append malicious URLs
        run: |
          curl -sSf https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-links-ACTIVE.txt >> maliciousURLs.txt
          MALICIOUS_URLS=$(curl -sSf https://urlhaus.abuse.ch/downloads/text/)
          echo "$MALICIOUS_URLS" >> maliciousURLs.txt

      - name: Remove duplicate lines
        run: |
          awk '!seen[$0]++' maliciousURLs.txt > temp.txt
          mv temp.txt maliciousURLs.txt

      - name: Remove lines starting with #
        run: |
          awk '!/^#/' maliciousURLs.txt > temp.txt
          mv temp.txt maliciousURLs.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "umairnehri9747@gmail.com"
          git config --global user.name "Umair Nehri - GitHub Actions"

          git add maliciousURLs.txt
          git commit -m "Update malicious URLs [skip ci]"
          git push
